### ISSUE TITLE
"HTML" stats goes away

### ISSUE THREAD

**Issue by michbsd** [varnish/libvmod-rtstatus#10]
Hi, 

Am running 4.1 branch.
After startup the page displays correctly with counters etc etc.. 

After a little while the page is just empty (see attached)
However if I open the json page, all stats are displayed correctly. Any ideas? 

![screen shot 2015-10-28 at 09 34 52](https://cloud.githubusercontent.com/assets/8202334/10783492/87ede862-7d58-11e5-9423-00da83fb2d2b.png)

**Comment by aondio** [comment]
Hi,
which browser are you using?
Also, can you please tell me what kind of error you get when checking "inspect element->console"?

**Comment by michbsd** [comment]
I am using Safari 9.x 

Attached is a screenshot of the console (the last line keeps incrementing, so it just runs in a sort of infinite loop) 

![screen_shot_2015-10-28_at_18_02_55](https://cloud.githubusercontent.com/assets/8202334/10796449/836ce798-7d9e-11e5-9a22-d6e56c7c5ae4.png)

**Comment by aondio** [comment]
Hi,
I'll try to reproduce and fix it.
I have tested the front page with the intention of supporting it only for
Firefox and Chrome, so please use one of these two if you can.

On Wed, Oct 28, 2015 at 6:05 PM, michbsd <notifications@github.com> wrote:

> I am using Safari 9.x
>
> Attached is a screenshot of the console (the last line keeps incrementing,
> so it just runs in a sort of infinite loop)
>
> [image: screen_shot_2015-10-28_at_18_02_55]
> <https://cloud.githubusercontent.com/assets/8202334/10796449/836ce798-7d9e-11e5-9a22-d6e56c7c5ae4.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/varnish/libvmod-rtstatus/issues/10#issuecomment-151911397>
> .
>



-- 
Arianna Aondio
Software Developer | Varnish Software AS
Mobile: +47 98062619
We Make Websites Fly
www.varnish-software.com
<http://info.varnish-software.com/signature>

**Comment by michbsd** [comment]
Thanks, will do.

But the same thing happens with Chrome  : 

![screen shot 2015-10-29 at 12 39 09](https://cloud.githubusercontent.com/assets/8202334/10817452/2cfd6d3c-7e3a-11e5-8280-950435d2ab7b.png)

**Comment by aondio** [comment]
That's not expected.
I'll look into that and get back to you.
Thank you for reporting it.

On Thu, Oct 29, 2015 at 12:40 PM, michbsd <notifications@github.com> wrote:

> Thanks, will do.
>
> But the same thing happens with Chrome :
>
> [image: screen shot 2015-10-29 at 12 39 09]
> <https://cloud.githubusercontent.com/assets/8202334/10817452/2cfd6d3c-7e3a-11e5-8280-950435d2ab7b.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/varnish/libvmod-rtstatus/issues/10#issuecomment-152154516>
> .
>



-- 
Arianna Aondio
Software Developer | Varnish Software AS
Mobile: +47 98062619
We Make Websites Fly
www.varnish-software.com
<http://info.varnish-software.com/signature>

**Comment by aondio** [comment]
Hi,
how often does it happen? does it "disappear" and appear again after a while?
I've tried to reproduce it but it work fine for me on both firefox and chrome.

**Comment by michbsd** [comment]
Well.. it worked for a few hours after reloading the VCL (adding your vmod).
Since then it has not worked.

the JSON stats are correctly updated though.

**Comment by michbsd** [comment]
Quick update - had to restart varnish yesterday - and everything seems to work for now.
will keep my eyes open, should the main page "disappear" again

**Comment by aondio** [comment]
Thanks for the update.
I'll close this issue now, feel free to open a new one if the issue raises again.
