### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by yk1711** [varnish/libvmod-rtstatus#13]
As I understand, I have to `./autogen.sh` to install the mod ?

In case I'm right, it returns this error:
```
Package varnishapi was not found in the pkg-config search path.
Perhaps you should add the directory containing `varnishapi.pc'
to the PKG_CONFIG_PATH environment variable
```

**Comment by adeelshahid** [comment]
Please run the following on Ubuntu/Debian.

These are needed for vmod development.

```sh
$> sudo apt-get install -y pkg-config libvarnishapi1 libvarnishapi-dev autotools-dev
```

After installation try running

```sh
$> ./autogen.sh
$> ./configure
$> make
# make install
```

Please note that `make install` is with a # at the front so you need sudo privileges to execute that command. It would copy vmod into the required varnish modules directory (/usr/lib/varnish/vmods).

### Note: 
you need to clone *libvmod-rt* (4.0 / 4.1) branch depending on the version of Varnish Cache installed.

@yk1711 I assume you have Ubuntu/Debian. Let me know if you are running Centos or any other distribution.

Hopefully it fixes the installation issues. If still have problems feel free to communicate back.

**Comment by adeelshahid** [comment]
### Centos

you need to be **sudo** to run these,

```sh
# yum group install -y "Development Tools"
# yum install -y varnish-libs varnish-libs-devel
# yum install -y docutils
```

Commands:

1st  will install necessary development tools.
2nd will install Varnish libraries for working with vmods.
3rd will install rst2man to generate documentation for vmod.

Next run the following commands,

```sh
$> ./autogen.sh
$> ./configure
$> make
# make install
```

If you find issues during ./configure for VARNISH_VMOD_DIR command not found. This means `/usr/share/aclocal/varnish.m4` is missing.

If you run into *pkg-config* problems on Centos, create a file */usr/lib64/pkgconfig/varnishapi.pc* with the following contents.

```ini
prefix=/usr
exec_prefix=/usr
bindir=/usr/bin
sbindir=/usr/sbin
libdir=/usr/lib64
includedir=/usr/include
pkgincludedir=${includedir}/varnish
datarootdir=${prefix}/share
datadir=/usr/share
pkgdatadir=${datadir}/varnish
vmoddir=${libdir}/varnish/vmods
vmodtool=${pkgdatadir}/vmodtool.py

Name: VarnishAPI
Description: Varnish API
Version: 4.0.3
Cflags: -I${includedir}/varnish
Libs: -L${libdir} -lvarnishapi
```
