### ISSUE TITLE
Trailing comma in be_info array

### ISSUE THREAD

**Issue by knuthaug** [varnish/libvmod-rtstatus#26]
Hi

Trying to parse the json output from rtstatus.json all json parsers I have tried complain about the trailing comma in the array of backends (be_info). AFAIK the json spec also disallows trailing commas in arrays. Any chance of a quick fix for this?

**Comment by daghf** [comment]
@aondio please have a look at this when you get around to it

**Comment by aondio** [comment]
Hi @knuthaug, which branch are you using?

**Comment by knuthaug** [comment]
I have no idea, installed by the guys in Redpill-Linpro. Maybe @JoarJ or @obliadp knows?

**Comment by aondio** [comment]
Hi,
Can you also please tell me how you define backends and directors?

I've tried to reproduce this with VC4.1 and using the branch 4.1 of this vmod and I didn't encounter any error.

**Comment by obliadp** [comment]
try VCP4.1 :-)

**Comment by aondio** [comment]
I've discussed this on IRC with Orjan(not sure which is his github name) and turned out that they where running a too old version of this vmod.
Branch 4.1, starting from commit 3fa94e7 is no longer affected.
Closing.
