### ISSUE TITLE
Support for Varnish 5

### ISSUE THREAD

**Issue by lukaszlach** [varnish/libvmod-rtstatus#27]
Is there a plan to modify this VMOD to support Varnish 5?

**Comment by aondio** [comment]
Hi @lukaszlach,
this VMOD will be ported to version 5, but not in the near future.
I'll open an issue and assign it to me.

As usual, patches are welcome :)

**Comment by breisig** [comment]
Any update on this support? It's been 6 months and still no support for the latest 5.xx series [5.2.1 currently]

**Comment by aondio** [comment]
Hi @breisig,
this task has very low priority on my to-do list at the moment.
If you want you can give it a go and I'll review it.

**Comment by gquintard** [comment]
not gonna happen as 5.x is EOL, focus is on #33
