### ISSUE TITLE
Varnish 6.0.2 Support

### ISSUE THREAD

**Issue by philipseidel** [varnish/libvmod-rtstatus#33]
I am unable to compile on Varnish 6.0.2.
[libvmod-rtstatus.txt](https://github.com/varnish/libvmod-rtstatus/files/2727968/libvmod-rtstatus.txt)

**Comment by thatsk** [comment]
why its not compiling

**Comment by gquintard** [comment]
"fixed", in the sense that I had to import some private headers from varnish. But those are fairly stable, so that should work.

checkout branch `6.0`
