### ISSUE TITLE
Configuration updates gives assertion errors with libvmod-rtstatus when updating backends/probes

### ISSUE THREAD

**Issue by anordby** [varnish/libvmod-rtstatus#7]
I am using Varnish 4.0.3 in Red Hat 7.1 x64 on VmWare. I am having some issues with libvmod-rtstatus when adding a lot of backends and probes. In this case I want to adress the assertion error I get: Child (1915) Panic message:
Assert error in WS_Release(), cache/cache_ws.c line 223:
  Condition(bytes <= ws->e - ws->f) not true.

Workspace problem? I tried to increase workspace_session from the default of bytes to 8192 bytes. No effect.

Full backtrace: https://mail.fupp.net/ssldist/vmod-rtstatus-messages.txt

**Comment by aondio** [comment]
Hi,
how many backends do you have?

**Comment by anordby** [comment]
This seems to happen somewhere between 16 and 20 backends (of which all are running probes). I am using the same probe for sets of two backends.
